---

- include_vars:
    file: "{{ vars_path }}"
  tags: always

- name: Create uWSGI user
  user:
    name: uwsgi
    groups: adm
    shell: /sbin/nologin
    append: yes
    state: present

###########################
# Application preparation #
###########################

- name: Pre-create dirs
  file: path={{ item }} owner={{ user }} state=directory
  with_items: "{{ app_dirs }}"

- name: Copy app files
  copy: src={{ item.src }} dest={{ item.dst }} owner={{ user }}
  with_items: "{{ app_files }}"

- name: Copy app templates
  template: src={{ item.src }} dest={{ item.dst }} owner={{ user }}
  with_items: "{{ app_templates }}"

####################
# Pip installation #
####################

- name: Install pip
  apt: name=python-pip state=latest
  register: install_pip

- name: Upgrade pip
  command: pip install --upgrade pip
  register: upgrade_pip
  when: install_pip|succeeded

######################
# uWSGI installation #
######################

- name: Install uWSGI
  pip: name=uwsgi
  register: install_uwsgi
  when: install_pip|succeeded

##################
# System service #
##################

- name: Add app init
  template: src=uwsgi.j2 dest=/etc/init.d/uwsgi mode=+x
  when: install_uwsgi|succeeded

- name: Update rc
  command: update-rc.d uwsgi defaults
  notify:
    - Start uWSGI

###############
# Logrotating #
###############

- name: Add logrotating
  template: src=app-logs.j2 dest=/etc/logrotate.d/app

